package View;

import Model.QLNhoMatKhau;
import Controller.Control_NhoMatKhau;
import Controller.LogginDAO;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;

import java.awt.event.KeyListener;
import java.awt.image.BufferedImage;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.util.List;
import java.util.Properties;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class frmLoggin extends javax.swing.JFrame {

    int i = 0;
    int isselect;
    FileReader fr;
    Properties pr;
    Controller.Control_NhoMatKhau ql = new Control_NhoMatKhau();
    String account, pass;
    boolean state = false;

    private static final String FILE_NAME = "rememberaccount.properties";
    private static final String ACCOUNT_KEY = "account";
    private static final String PASSWORD_KEY = "pass";
    private static final String STATE_KEY = "state";

    /**
     * Creates new form frmLoggin
     */
    public frmLoggin() {
        initComponents();
        initUI();
        getFileRememberAccount();
    }

    private void getFileRememberAccount() {
        try {
            fr = new FileReader(FILE_NAME);
            pr = new Properties();
            pr.load(fr);
            // System.out.println(pr.getProperty("account") + " " + pr.getProperty("pass"));
            account = pr.getProperty(ACCOUNT_KEY);
            pass = pr.getProperty(PASSWORD_KEY);
            state = Boolean.parseBoolean(pr.getProperty(STATE_KEY));
            getREMpass();
            fr.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void getREMpass() {
        if (state) {
            txtMatkhau.setText(pass);
            txtTaikhoan.setText(account);
            chkNhoMatKHau.setSelected(state);
        }
    }

    public void initUI() {
        this.setBackground(Color.white);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        txtTaikhoan.addKeyListener(new CustomkeyListener());
        txtMatkhau.addKeyListener(new CustomkeyListener());
        btnLoggin.setBackground(Color.getHSBColor(255, 255, 255));
        btnSignin.setBackground(Color.white);
        isselect = 1;
        txtMatkhau.setEchoChar('*');
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnLoggin = new javax.swing.JButton();
        btnSignin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTaikhoan = new javax.swing.JTextField();
        txtMatkhau = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        chkNhoMatKHau = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 514, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLoggin.setBackground(new java.awt.Color(255, 255, 255));
        btnLoggin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLoggin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2.png"))); // NOI18N
        btnLoggin.setBorderPainted(false);
        btnLoggin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoggin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogginMouseEntered(evt);
            }
        });
        btnLoggin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogginActionPerformed(evt);
            }
        });
        btnLoggin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLogginKeyPressed(evt);
            }
        });
        jPanel2.add(btnLoggin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 170, 60));

        btnSignin.setBackground(new java.awt.Color(255, 255, 255));
        btnSignin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSignin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dangky.png"))); // NOI18N
        btnSignin.setBorderPainted(false);
        btnSignin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigninActionPerformed(evt);
            }
        });
        jPanel2.add(btnSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 430, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 170, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loin1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, -10, 120, 150));

        txtTaikhoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTaikhoan.setText("username");
        txtTaikhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTaikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTaikhoanMouseClicked(evt);
            }
        });
        txtTaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaikhoanActionPerformed(evt);
            }
        });
        jPanel2.add(txtTaikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 310, 40));

        txtMatkhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(txtMatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 260, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2_2.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 40, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1_1.jpg"))); // NOI18N
        jLabel5.setText("jLabel4");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 40, 30));

        jPanel4.setLayout(new java.awt.CardLayout());
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        chkNhoMatKHau.setBackground(new java.awt.Color(255, 255, 255));
        chkNhoMatKHau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkNhoMatKHau.setText("NHỚ MẬT KHẨU");
        chkNhoMatKHau.setBorder(null);
        chkNhoMatKHau.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chkNhoMatKHau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNhoMatKHauActionPerformed(evt);
            }
        });
        jPanel2.add(chkNhoMatKHau, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 140, 30));

        jLabel6.setText("jLabel4");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 40, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/19_19.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 50, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (isselect == 1) {
            txtMatkhau.setEchoChar((char) 0);
            isselect = 0;
            jLabel3.setIcon(new ImageIcon("C:\\Users\\DELL\\Documents\\NetBeansProjects\\TongHopForm\\src\\Images\\icons8-hide-45.png"));
        } else if (isselect == 0) {
            txtMatkhau.setEchoChar('*');
            isselect = 1;
            jLabel3.setIcon(new ImageIcon("C:\\Users\\DELL\\Documents\\NetBeansProjects\\TongHopForm\\src\\Images\\19_19.png"));
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtTaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaikhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaikhoanActionPerformed

    private void txtTaikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTaikhoanMouseClicked

    }//GEN-LAST:event_txtTaikhoanMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int check = JOptionPane.showConfirmDialog(rootPane, "Xác nhận thoát?", "Cảnh báo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (check == 0) {
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigninActionPerformed
        frmSignin f1 = new frmSignin();
        f1.setVisible(true);
        //        frmLoggin f2 = new frmLoggin();
        //        f2.setVisible(true);
    }//GEN-LAST:event_btnSigninActionPerformed

    private void btnLogginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLogginKeyPressed

    }//GEN-LAST:event_btnLogginKeyPressed

    private void btnLogginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogginActionPerformed
        logginlistener();
    }//GEN-LAST:event_btnLogginActionPerformed

    private void logginlistener(){
        
        LogginDAO lgd = new LogginDAO();
        String tk = txtTaikhoan.getText();
        if (lgd.get(txtTaikhoan.getText(), String.valueOf(txtMatkhau.getPassword()))) {
//            if (chkNhoMatKHau.isSelected()) {
//                ql.update(new QLNhoMatKhau(1, "roi", txtTaikhoan.getText(), String.valueOf(txtMatkhau.getPassword())));
//            } else {
//                ql.update(new QLNhoMatKhau(1, "chua", txtTaikhoan.getText(), String.valueOf(txtMatkhau.getPassword())));
//            }
            try {
                FileOutputStream out = new FileOutputStream(FILE_NAME);

                if (chkNhoMatKHau.isSelected()) {
                    pr.setProperty(ACCOUNT_KEY, txtTaikhoan.getText().toString().trim() + "");
                    pr.setProperty(PASSWORD_KEY, txtMatkhau.getText().toString().trim() + "");
                }
                pr.setProperty(STATE_KEY, String.valueOf(chkNhoMatKHau.isSelected()));
                pr.store(out, null);
                out.close();
                frmMain f1 = new frmMain(tk);
                JOptionPane.showMessageDialog(rootPane, "Đăng nhập thành công", "Chúc mừng", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                f1.setVisible(true);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Tài khoản hoặc mật khẩu không đúng", "Đăng nhập thất bại", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void btnLogginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogginMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogginMouseEntered

    private void chkNhoMatKHauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNhoMatKHauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkNhoMatKHauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLoggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLoggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLoggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLoggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLoggin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggin;
    private javax.swing.JButton btnSignin;
    private javax.swing.JCheckBox chkNhoMatKHau;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField txtMatkhau;
    private javax.swing.JTextField txtTaikhoan;
    // End of variables declaration//GEN-END:variables
    class CustomkeyListener implements KeyListener {

        @Override
        public void keyTyped(KeyEvent e) {
        }

        @Override
        public void keyPressed(KeyEvent e) {
            if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                logginlistener();
            }
        }

        @Override
        public void keyReleased(KeyEvent e) {
        }
    }
}
