/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import java.awt.Desktop;
import javax.print.attribute.standard.Destination;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain1
     */
    String tentaikhoan;

    public frmMain() {
        initComponents();
        initUI();
    }

    public frmMain(String tentaikhoan) {
        initComponents();
        initUI();
        this.tentaikhoan = tentaikhoan;

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        Desktop = new javax.swing.JDesktopPane();
        interThongTinNguoiDung = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miQLNguoiDung = new javax.swing.JMenuItem();
        miDoimatkhau = new javax.swing.JMenuItem();
        miDangxuat = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        miQLDichvu = new javax.swing.JMenuItem();
        miQLPhong = new javax.swing.JMenuItem();
        miQLKhachhang = new javax.swing.JMenuItem();
        miQLHoadon = new javax.swing.JMenuItem();
        miQLNhanvien = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        miTrogiupphanmem = new javax.swing.JMenuItem();
        miLienhe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");

        Desktop.setBackground(new java.awt.Color(153, 204, 255));
        Desktop.setForeground(new java.awt.Color(0, 153, 255));

        interThongTinNguoiDung.setVisible(false);

        javax.swing.GroupLayout interThongTinNguoiDungLayout = new javax.swing.GroupLayout(interThongTinNguoiDung.getContentPane());
        interThongTinNguoiDung.getContentPane().setLayout(interThongTinNguoiDungLayout);
        interThongTinNguoiDungLayout.setHorizontalGroup(
            interThongTinNguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        interThongTinNguoiDungLayout.setVerticalGroup(
            interThongTinNguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Desktop.setLayer(interThongTinNguoiDung, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(interThongTinNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1300, Short.MAX_VALUE))
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(interThongTinNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(747, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hethong.png"))); // NOI18N
        jMenu1.setText("Hệ thống");

        miQLNguoiDung.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        miQLNguoiDung.setText("Quản lý người dùng");
        miQLNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miQLNguoiDungActionPerformed(evt);
            }
        });
        jMenu1.add(miQLNguoiDung);

        miDoimatkhau.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        miDoimatkhau.setText("Đổi mật khẩu");
        miDoimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDoimatkhauActionPerformed(evt);
            }
        });
        jMenu1.add(miDoimatkhau);

        miDangxuat.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        miDangxuat.setText("Đăng xuất");
        miDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDangxuatActionPerformed(evt);
            }
        });
        jMenu1.add(miDangxuat);

        jMenuBar1.add(jMenu1);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manage.png"))); // NOI18N
        jMenu6.setText("Quản lí");

        miQLDichvu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        miQLDichvu.setText("Quản lí dịch vụ");
        miQLDichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miQLDichvuActionPerformed(evt);
            }
        });
        jMenu6.add(miQLDichvu);

        miQLPhong.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        miQLPhong.setText("Quản lí phòng");
        miQLPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miQLPhongActionPerformed(evt);
            }
        });
        jMenu6.add(miQLPhong);

        miQLKhachhang.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        miQLKhachhang.setText("Quản lí khách hàng");
        miQLKhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miQLKhachhangActionPerformed(evt);
            }
        });
        jMenu6.add(miQLKhachhang);

        miQLHoadon.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        miQLHoadon.setText("Quản lí hóa đơn");
        miQLHoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miQLHoadonActionPerformed(evt);
            }
        });
        jMenu6.add(miQLHoadon);

        miQLNhanvien.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        miQLNhanvien.setText("Quản lí nhân viên");
        miQLNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miQLNhanvienActionPerformed(evt);
            }
        });
        jMenu6.add(miQLNhanvien);

        jMenuBar1.add(jMenu6);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chart-icon.png"))); // NOI18N
        jMenu2.setText("Thống kê");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Phone-icon.png"))); // NOI18N
        jMenu7.setText("Trợ giúp");

        miTrogiupphanmem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        miTrogiupphanmem.setText("Trợ giúp phần mềm");
        miTrogiupphanmem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTrogiupphanmemActionPerformed(evt);
            }
        });
        jMenu7.add(miTrogiupphanmem);

        miLienhe.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        miLienhe.setText("Liên hệ");
        miLienhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLienheActionPerformed(evt);
            }
        });
        jMenu7.add(miLienhe);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miDoimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDoimatkhauActionPerformed
        mdiDoiMatKhau mdidoimatkhau = new mdiDoiMatKhau(tentaikhoan);
        Desktop.add(mdidoimatkhau);
        mdidoimatkhau.setLocation((Desktop.getHeight() - mdidoimatkhau.getHeight()) / 2,
                (Desktop.getWidth() - mdidoimatkhau.getWidth()) / 2);
        mdidoimatkhau.setVisible(true);
    }//GEN-LAST:event_miDoimatkhauActionPerformed

    private void miDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDangxuatActionPerformed
        int check = JOptionPane.showConfirmDialog(rootPane, "Xác nhận đăng xuất?", "Cảnh báo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (check == 0) {
            dispose();
            frmLoggin floggin = new frmLoggin();
            floggin.setVisible(true);
        }
    }//GEN-LAST:event_miDangxuatActionPerformed

    private void miQLNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miQLNguoiDungActionPerformed
        mdiThongTinNguoiDung mdithongtinnguoidung = new mdiThongTinNguoiDung(tentaikhoan);
        Desktop.add(mdithongtinnguoidung);
        mdithongtinnguoidung.setLocation((Desktop.getHeight() - mdithongtinnguoidung.getHeight()) / 2,
                (Desktop.getWidth() - mdithongtinnguoidung.getWidth()) / 2);
        mdithongtinnguoidung.setVisible(true);
    }//GEN-LAST:event_miQLNguoiDungActionPerformed

    private void miQLDichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miQLDichvuActionPerformed
        mdiDichVu m1 = new mdiDichVu();
        Desktop.add(m1);
        m1.setLocation((Desktop.getHeight() - m1.getHeight()) / 2,
                (Desktop.getWidth() - m1.getWidth()) / 2);
        m1.setVisible(true);
    }//GEN-LAST:event_miQLDichvuActionPerformed

    private void miQLPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miQLPhongActionPerformed
        mdiPhong m1 = new mdiPhong();
        Desktop.add(m1);
        m1.setLocation((Desktop.getHeight() - m1.getHeight()) / 2,
                (Desktop.getWidth() - m1.getWidth()) / 2);
        m1.setVisible(true);
    }//GEN-LAST:event_miQLPhongActionPerformed

    private void miQLKhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miQLKhachhangActionPerformed
        mdiQuanLiKhachHang m1 = new mdiQuanLiKhachHang();
        Desktop.add(m1);
        m1.setLocation((Desktop.getHeight() - m1.getHeight()) / 2,
                (Desktop.getWidth() - m1.getWidth()) / 2);
        m1.setVisible(true);
    }//GEN-LAST:event_miQLKhachhangActionPerformed

    private void miQLHoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miQLHoadonActionPerformed
        mdiHoaDon m1 = new mdiHoaDon();
        Desktop.add(m1);
        m1.setLocation((Desktop.getHeight() - m1.getHeight()) / 2,
                (Desktop.getWidth() - m1.getWidth()) / 2);
        m1.setVisible(true);
    }//GEN-LAST:event_miQLHoadonActionPerformed

    private void miQLNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miQLNhanvienActionPerformed
        mdiNhanVien m1 = new mdiNhanVien();
        Desktop.add(m1);
        m1.setLocation((Desktop.getHeight() - m1.getHeight()) / 2,
                (Desktop.getWidth() - m1.getWidth()) / 2);
        m1.setVisible(true);
    }//GEN-LAST:event_miQLNhanvienActionPerformed

    private void miTrogiupphanmemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTrogiupphanmemActionPerformed
        mdiTroGiupPhanMem m1 = new mdiTroGiupPhanMem();
        Desktop.add(m1);
        m1.setLocation((Desktop.getHeight() - m1.getHeight()) / 2,
                (Desktop.getWidth() - m1.getWidth()) / 2);
        m1.setVisible(true);
    }//GEN-LAST:event_miTrogiupphanmemActionPerformed

    private void miLienheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLienheActionPerformed
        mdiLienHe m1 = new mdiLienHe();
        Desktop.add(m1);
        m1.setLocation((Desktop.getHeight() - m1.getHeight()) / 2,
                (Desktop.getWidth() - m1.getWidth()) / 2);
        m1.setVisible(true);
    }//GEN-LAST:event_miLienheActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        frmThongKe m1 = new frmThongKe();
        m1.setLocationRelativeTo(null);
        m1.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JInternalFrame interThongTinNguoiDung;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JMenuItem miDangxuat;
    private javax.swing.JMenuItem miDoimatkhau;
    private javax.swing.JMenuItem miLienhe;
    private javax.swing.JMenuItem miQLDichvu;
    private javax.swing.JMenuItem miQLHoadon;
    private javax.swing.JMenuItem miQLKhachhang;
    private javax.swing.JMenuItem miQLNguoiDung;
    private javax.swing.JMenuItem miQLNhanvien;
    private javax.swing.JMenuItem miQLPhong;
    private javax.swing.JMenuItem miTrogiupphanmem;
    // End of variables declaration//GEN-END:variables

    private void initUI() {
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        JLabel lbback;
//        this.setSize(600,600);
//        Desktop.setSize(600,600);
//        Desktop.setLayout(null);
//        ImageIcon img = new ImageIcon("C:\\Users\\DELL\\Documents\\NetBeansProjects\\TongHopForm\\src\\Images\\eb3ef-logo-utt-noborder.png");
//        lbback = new JLabel("",img,JLabel.CENTER);
//        lbback.setBounds(0,0,600,600);
//        Desktop.add(lbback); 
    }
}
