/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import CustomComponent.Country;
import Model.QLKhachHang;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class frmThemKhachHang extends javax.swing.JFrame {

    private final String regexStr = "^[0-9]*$";
    private int xDrag,yDrag,xPress,yPress;
    String tenkh,cmnd,quoctich,gioitinh,sdt,maphong,manv,ngaydat,ngaytra;
    List<QLKhachHang> ds_khachang;
    int tuoi,cbIndex;
    
    public frmThemKhachHang() {
        initComponents();
        btnSua.setVisible(false);
        btnXoa.setVisible(false);
        bg.add(rdNu);
        bg.add(rdNam);
        //System.out.println(checkPhoneNumber("21341234123543"));
    }
    
//    public frmThemKhachHang(String maphong,String manv,String ngaydat,String ngaytra,List<QLKhachHang> ds_khachang){
//        initComponents();
//        this.maphong = maphong;
//        this.manv = manv;
//        this.ngaydat = ngaydat;
//        this.ngaytra = ngaytra;
//        this.ds_khachang = ds_khachang;
//        bg.add(rdNu);
//        bg.add(rdNam);
//        //JOptionPane.showMessageDialog(rootPane,maphong + manv + ngaydat + ngaytra,"Success?",JOptionPane.INFORMATION_MESSAGE);
//    }
    
    public frmThemKhachHang(String tenkh,String cmnd,String quoctich,String gioitinh,String sdt,int tuoi,int cbIndex){
        initComponents();
        this.tenkh = tenkh;
        this.cmnd = cmnd;
        this.quoctich = quoctich;
        this.gioitinh = gioitinh;
        this.sdt = sdt;
        this.tuoi = tuoi;
        this.cbIndex = cbIndex;
        btnThem.setVisible(false);
        txtTenKH.setText(tenkh);
        txtCMND.setText(cmnd);
        cbQuocTich.setSelectedIndex(cbIndex);
        txtSDT.setText(sdt);
        txtTuoi.setText(tuoi + "");
        if(gioitinh.toUpperCase().equals("NAM")){
            rdNam.setSelected(true);
        }
        else{
            rdNu.setSelected(true);
        }
        bg.add(rdNu);
        bg.add(rdNam);
        //JOptionPane.showMessageDialog(rootPane,maphong + manv + ngaydat + ngaytra,"Success?",JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void resetData(){
        txtCMND.setText("");
        cbQuocTich.setSelectedIndex(0);
        txtSDT.setText("");
        txtTenKH.setText("");
        txtTuoi.setText("");
        txtTenKH.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        txtTuoi = new javax.swing.JTextField();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnKetThuc = new javax.swing.JButton();
        txtSDT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cbQuocTich = new javax.swing.JComboBox<>();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin chi tiết"));

        jLabel2.setText("Tên KH");

        jLabel3.setText("CMND");

        jLabel4.setText("QUỐC TỊCH");

        jLabel5.setText("GIỚI TÍNH");

        jLabel6.setText("TUỔI");

        jLabel7.setText("SDT");

        rdNam.setSelected(true);
        rdNam.setText("NAM");

        rdNu.setText("NỮ");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnKetThuc.setText("Kết thúc");
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbQuocTich.setModel(new DefaultComboBoxModel<>(Country.createCountrylist()));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(52, 52, 52)
                                .addComponent(txtTenKH))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCMND)
                                    .addComponent(cbQuocTich, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(80, 80, 80)
                                .addComponent(rdNam)
                                .addGap(47, 47, 47)
                                .addComponent(rdNu)
                                .addGap(0, 137, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(64, 64, 64)
                                .addComponent(txtTuoi))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(67, 67, 67)
                                .addComponent(txtSDT))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2))
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3))
                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addComponent(rdNam)
                    .addComponent(rdNu))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6))
                    .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7))
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKetThuc)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if(getData()){
        mdiDatPhong.addRowToTblKhachHang(new Object[]{
            tenkh,
            cmnd,
            quoctich,
            gioitinh,
            tuoi,
            sdt
        });
        mdiDatPhong.indexOfComboCountry.add(cbQuocTich.getSelectedIndex());
            System.out.println(cbQuocTich.getSelectedIndex());
        resetData();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private boolean getData(){
        boolean check = true;
        tenkh = txtTenKH.getText().toString().trim();
        cmnd = txtCMND.getText().toString().trim();
        quoctich = cbQuocTich.getSelectedItem().toString();
        sdt = txtSDT.getText().toString().trim();
        
        if(rdNam.isSelected()){
            gioitinh = "Nam";
        }
        else{
            gioitinh = "Nu";
        }
        
        if (tenkh.length() <= 0) {
            check = false;
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập tên khách hàng", "Cập nhật thất bại", JOptionPane.WARNING_MESSAGE);
        } else if (cmnd.length() <= 0) {
            check = false;
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập CMND", "Cập nhật thất bại", JOptionPane.WARNING_MESSAGE);
        } else if (cbQuocTich.getSelectedIndex()<=0) {
            check = false;
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập quốc tịch", "Cập nhật thất bại", JOptionPane.WARNING_MESSAGE);
        } else if (txtTuoi.getText().toString().trim().length() <= 0) {
            check = false;
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập tuổi", "Cập nhật thất bại", JOptionPane.WARNING_MESSAGE);
        } else if (sdt.length() <= 0 || !checkPhoneNumber(sdt)) {
            check = false;
            JOptionPane.showMessageDialog(rootPane, "Số điện thoại sai định dạng", "Cập nhật thất bại", JOptionPane.WARNING_MESSAGE);
        } else if (txtTuoi.getText().toString().trim().length() > 0) {
            try {
                tuoi = Integer.parseInt(txtTuoi.getText().toString().trim());
                if (tuoi <= 0 || tuoi > 200) {
                    JOptionPane.showMessageDialog(rootPane, "Tuổi nhập sai định dạng", "Cập nhật thất bại", JOptionPane.WARNING_MESSAGE);
                    check = false;
                }
//                if(checkTuoi > 200){
//                    JOptionPane.showMessageDialog(rootPane, "Tuổi nhập sai định dạng", "Cập nhật thất bại", JOptionPane.WARNING_MESSAGE);
//                    check = false;
//                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Tuổi nhập sai định dạng", "Cập nhật thất bại", JOptionPane.WARNING_MESSAGE);
                check = false;
            }
        }
        return check;
    }
    
//     private boolean KiemtraDK() {
//        boolean check = true;
//        
//        return check;
//    }
    
    private boolean checkPhoneNumber(String setnum){
        return setnum.matches(regexStr);
    }
    
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if(getData()){
        mdiDatPhong.updateRowToTblKhachHang(tenkh, cmnd, quoctich, gioitinh, sdt, tuoi,cbQuocTich.getSelectedIndex());
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        int check = JOptionPane.showConfirmDialog(rootPane, "Xác nhận thoát?", "Cảnh báo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (check == 0) {
            frmThemKhachHang.this.dispose();
        }
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        resetData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        xDrag = evt.getX();
         yDrag = evt.getY();
        JFrame jFrame = (JFrame) evt.getSource();
        frmThemKhachHang.this.setLocation(jFrame.getLocation().x+xDrag-xPress,jFrame.getLocation().y+yDrag-yPress);
    }//GEN-LAST:event_formMouseDragged

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        xPress = evt.getX();
        yPress = evt.getY();
    }//GEN-LAST:event_formMouseMoved

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        mdiDatPhong.deleteRowTblKhachHang();
        frmThemKhachHang.this.dispose();
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmThemKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<Country> cbQuocTich;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables
}
