/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Control_QlPhong;
import Controller.Control_TK_Phong;
import Model.QlPhong;
import Model.ThongKe_Phong;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author DELL
 */
public class frmThongKe extends javax.swing.JFrame {

    int xDrag, yDrag, xPress, yPress;
    /**
     * Creates new form frmThongKe
     */
    ArrayList<ThongKe_Phong> tkpbds_ds = new ArrayList<>();
    Controller.Control_TK_Phong thongKePhongByDay = new Control_TK_Phong();
    Controller.Control_QlPhong qp = new Control_QlPhong();
    String tenThongso = "Chú thích";
    // float maxdayofmonth = 101;
    String dayFrom, dayTo;
    String maphong;
    int type = 0, nam = 0;

    public frmThongKe() {
        initComponents();
        setComboPhong();
    }

    private float getKhoangCachNgay(String dayfrom, String dayto) {
        long diff = 0;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date date1 = sdf.parse(dayfrom);
            Date date2 = sdf.parse(dayto);
            diff = date2.getTime() - date1.getTime();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return diff / (1000 * 60 * 60 * 24);
    }

    private void setComboPhong() {
        List<QlPhong> ds = qp.getAll();
        for (QlPhong d : ds) {
            cbChonPhong.addItem(d.getTenphong());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jdateDayFrom = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jdateDayTo = new com.toedter.calendar.JDateChooser();
        btnThongkeSoLan = new javax.swing.JButton();
        panelThongSoLan = new javax.swing.JPanel();
        cbType = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        cbChonPhong = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbChonNam = new javax.swing.JComboBox<>();
        fasg = new javax.swing.JPanel();
        pnThongKePhong = new javax.swing.JPanel();
        btnPhongThongKe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(802, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane3.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane3.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(" "));

        jdateDayFrom.setBackground(new java.awt.Color(0, 0, 0));
        jdateDayFrom.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ngày từ");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ngày đến");

        jdateDayTo.setBackground(new java.awt.Color(0, 0, 0));
        jdateDayTo.setForeground(new java.awt.Color(255, 255, 255));

        btnThongkeSoLan.setBackground(new java.awt.Color(0, 0, 0));
        btnThongkeSoLan.setForeground(new java.awt.Color(255, 255, 255));
        btnThongkeSoLan.setText("Thống kê");
        btnThongkeSoLan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongkeSoLanActionPerformed(evt);
            }
        });

        panelThongSoLan.setBackground(new java.awt.Color(255, 255, 255));
        panelThongSoLan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông số", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N
        panelThongSoLan.setForeground(new java.awt.Color(255, 255, 255));
        panelThongSoLan.setLayout(new javax.swing.BoxLayout(panelThongSoLan, javax.swing.BoxLayout.LINE_AXIS));

        cbType.setBackground(new java.awt.Color(0, 0, 0));
        cbType.setForeground(new java.awt.Color(255, 255, 255));
        cbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thống kê số lần đặt phòng", "Thống kê số ngày đặt phòng", "Thống kê doanh thu (Theo ngày đặt)", "Thống kê doanh thu (Theo ngày trả)" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdateDayFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdateDayTo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbType, 0, 282, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThongkeSoLan)
                .addContainerGap())
            .addComponent(panelThongSoLan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdateDayFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdateDayTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnThongkeSoLan)
                                .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelThongSoLan, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Tất cả", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(" "));

        cbChonPhong.setBackground(new java.awt.Color(0, 0, 0));
        cbChonPhong.setForeground(new java.awt.Color(255, 255, 255));
        cbChonPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Chọn phòng: ");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Chọn năm: ");

        cbChonNam.setBackground(new java.awt.Color(0, 0, 0));
        cbChonNam.setForeground(new java.awt.Color(255, 255, 255));
        cbChonNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000" }));

        fasg.setBackground(new java.awt.Color(255, 255, 255));
        fasg.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông số", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N
        fasg.setForeground(new java.awt.Color(0, 0, 0));

        pnThongKePhong.setBackground(new java.awt.Color(255, 255, 255));
        pnThongKePhong.setLayout(new javax.swing.BoxLayout(pnThongKePhong, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout fasgLayout = new javax.swing.GroupLayout(fasg);
        fasg.setLayout(fasgLayout);
        fasgLayout.setHorizontalGroup(
            fasgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThongKePhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fasgLayout.setVerticalGroup(
            fasgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThongKePhong, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        btnPhongThongKe.setBackground(new java.awt.Color(0, 0, 0));
        btnPhongThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btnPhongThongKe.setText("Thống kê");
        btnPhongThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhongThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbChonPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbChonNam, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnPhongThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(fasg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbChonPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(cbChonNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPhongThongKe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fasg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Từng phòng", jPanel2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 830, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        int check = JOptionPane.showConfirmDialog(rootPane, "Xác nhận thoát?", "Cảnh báo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (check == 0) {
            dispose();
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        xDrag = evt.getX();
        yDrag = evt.getY();
        JFrame jFrame = (JFrame) evt.getSource();
        frmThongKe.this.setLocation(jFrame.getLocation().x + xDrag - xPress, jFrame.getLocation().y + yDrag - yPress);
    }//GEN-LAST:event_formMouseDragged

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        xPress = evt.getX();
        yPress = evt.getY();
    }//GEN-LAST:event_formMouseMoved

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jPanel6.setBackground(Color.red);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jPanel6.setBackground(Color.black);
    }//GEN-LAST:event_jLabel3MouseExited

    private void btnThongkeSoLanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeSoLanActionPerformed
        loadChart(panelThongSoLan, cbType.getSelectedIndex());
    }//GEN-LAST:event_btnThongkeSoLanActionPerformed

    private void btnPhongThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhongThongKeActionPerformed
        if (cbChonNam.getSelectedIndex() > 0) {
            nam = Integer.parseInt(cbChonNam.getSelectedItem().toString());
        } else {
            nam = -1;
        }
        if (cbChonPhong.getSelectedIndex() > 0) {
            maphong = qp.getMaPhong(cbChonPhong.getSelectedIndex());
        } else {
            maphong = "all";
        }
        loadChart(pnThongKePhong, 4);
    }//GEN-LAST:event_btnPhongThongKeActionPerformed

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setBackground(Color.red);
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        jPanel6.setBackground(Color.black);
    }//GEN-LAST:event_jPanel6MouseExited

    /**
     * @param args the command line arguments
     */
    private boolean setValue(DefaultCategoryDataset dcd, int index) {
        boolean check = false;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        if (index == 4) {
            tkpbds_ds = (ArrayList<ThongKe_Phong>) thongKePhongByDay.getAllPricebyRoom(maphong, nam);
            for (ThongKe_Phong d : tkpbds_ds) {
                dcd.setValue(d.getValue(), "Tháng", d.getKey());
            }
            check = true;
        } else {
            try {
                dayFrom = sdf.format(jdateDayFrom.getDate());
                dayTo = sdf.format(jdateDayTo.getDate());
                if (getKhoangCachNgay(dayFrom, dayTo) < 0 || dayFrom.isEmpty() || dayTo.isEmpty()) {
                    JOptionPane.showMessageDialog(rootPane, "Chọn sai định dạng ngày", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    tkpbds_ds.clear();
                    if (index == 0) {
                        tkpbds_ds = (ArrayList<ThongKe_Phong>) thongKePhongByDay.getAllbyDay(dayFrom, dayTo);
                        for (ThongKe_Phong d : tkpbds_ds) {
                            dcd.setValue(d.getValue(), "Tên phòng", d.getKey());
                        }
                        check = true;
                    } else if (index == 1) {
                        tkpbds_ds = (ArrayList<ThongKe_Phong>) thongKePhongByDay.getAllDaysbyDay(dayFrom, dayTo);
                        for (ThongKe_Phong d : tkpbds_ds) {
                            dcd.setValue(d.getValue(), "Tên phòng", d.getKey());
                        }
                        check = true;
                    } else if (index == 2) {
                        tkpbds_ds = (ArrayList<ThongKe_Phong>) thongKePhongByDay.getAllPricebyDayFrom(dayFrom, dayTo);
                        for (ThongKe_Phong d : tkpbds_ds) {
                            dcd.setValue(d.getValue(), "Tên phòng", d.getKey());
                        }
                        check = true;
                    } else if (index == 3) {
                        tkpbds_ds = (ArrayList<ThongKe_Phong>) thongKePhongByDay.getAllPricebyDayTo(dayFrom, dayTo);
                        for (ThongKe_Phong d : tkpbds_ds) {
                            dcd.setValue(d.getValue(), "Tên phòng", d.getKey());
                        }
                        check = true;
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Chọn sai định dạng ngày", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
                check = false;
            }
        }
        return check;
    }

    private void loadChart(JPanel panel, int index) {
        String title = "";
        String verticalunit = "";
        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        if (index == 0) {
            title = "Thống kê số lượng lần";
            verticalunit = "Số lượng lần";
        } else if (index == 1) {
            title = "Thống kê số lượng ngày";
            verticalunit = "Số lượng ngày";
        } else if (index == 2) {
            title = "Thống kê doanh thu theo ngày đặt";
            verticalunit = "Doanh thu";
        } else if (index == 3) {
            title = "Thống kê doanh thu theo ngày trả";
            verticalunit = "Doanh thu";
        } else if (index == 4) {
            title = "Thống kê doanh thu theo từng phòng";
            verticalunit = "Doanh thu";
        }
        if (setValue(dcd, index)) {
            JFreeChart jcChart = ChartFactory.createBarChart(title, tenThongso, verticalunit, dcd, PlotOrientation.VERTICAL, true, true, false);
            CategoryPlot plot = jcChart.getCategoryPlot();
            plot.setRangeGridlinePaint(Color.BLACK);
            ChartFrame charfrFrame = new ChartFrame("Thống kê", jcChart, true);
            // charfrFrame.setVisible(true);
            charfrFrame.setSize(500, 400);
            ChartPanel chartPanel = new ChartPanel(jcChart);
            panel.removeAll();
            panel.add(chartPanel);
            panel.updateUI();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPhongThongKe;
    private javax.swing.JButton btnThongkeSoLan;
    private javax.swing.JComboBox<String> cbChonNam;
    private javax.swing.JComboBox<String> cbChonPhong;
    private javax.swing.JComboBox<String> cbType;
    private javax.swing.JPanel fasg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane3;
    private com.toedter.calendar.JDateChooser jdateDayFrom;
    private com.toedter.calendar.JDateChooser jdateDayTo;
    private javax.swing.JPanel panelThongSoLan;
    private javax.swing.JPanel pnThongKePhong;
    // End of variables declaration//GEN-END:variables
}
