/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Control_DatPhong;
import Controller.Control_QlDichVu;
import Controller.Control_QlKhachHang;
import Controller.Control_QlNhanVien;
import Controller.Control_QlPhong;
import Model.DatPhong;
import Model.QLKhachHang;
import Model.QLNhanVien;
import Model.QlDichVu;
import Model.QlPhong;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class mdiDatPhong extends javax.swing.JFrame {
    private int xDrag,yDrag,xPress,yPress;

    Control_DatPhong dp = new Control_DatPhong();
    Control_QlNhanVien nv = new Control_QlNhanVien();
    Control_QlPhong qp = new Control_QlPhong();
    Control_QlKhachHang qk = new Control_QlKhachHang();
    Control_QlDichVu dv = new Control_QlDichVu();
    static DefaultTableModel model = new DefaultTableModel();
    
    List<QLKhachHang> ds_khachhang;
    String maphong,manv,ngaydat,ngaytra;
    String tenkh,cmnd,quoctich,gioitinh,sdt;
    int tuoi;
    static List<Integer> indexOfComboCountry;
    /**
     * Creates new form mdiDatPhong
     */
    public mdiDatPhong() {
        initComponents();
        setComboNhanVien();
        setComboPhong();
        jdateNgaydat.setDate(new Date());
        indexOfComboCountry = new ArrayList<>();
    }
    
    
    private void setComboNhanVien(){
        List<QLNhanVien> ds = nv.getAll();
        for (QLNhanVien d : ds) {
            cbMaNV.addItem(d.getTennv());
        }
    }
    private void setComboPhong(){
        List<QlPhong> ds = qp.getAllWithEnable();
        for (QlPhong d : ds) {
            cbTenPhong.addItem(d.getTenphong());
        }
    }
    public int getNhanVienIndex(String manhanvien) {
        int i = 1;
        List<QLNhanVien> ds = nv.getAll();
        for (QLNhanVien d : ds) {
            if (d.getMnv().trim().equals(manhanvien)) {
                return i;
            }
            i++;
        }
        return -1;
    }
    public int getPhongIndex(String manhanvien) {
        int i = 1;
        List<QlPhong> ds = qp.getAll();
        for (QlPhong d : ds) {
            if (d.getMaphong().trim().equals(manhanvien)) {
                return i;
            }
            i++;
        }
        return -1;
    }
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbMaNV = new javax.swing.JComboBox<>();
        jdateNgaydat = new com.toedter.calendar.JDateChooser();
        btnXacNhan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jdateNgayTra = new com.toedter.calendar.JDateChooser();
        cbTenPhong = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ckcSuoiNong = new javax.swing.JCheckBox();
        ckcGiatLa = new javax.swing.JCheckBox();
        ckcMassage = new javax.swing.JCheckBox();
        ckcNhaHang = new javax.swing.JCheckBox();
        ckcTennis = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        btnThemKhachHang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jLabel3.setText("Ngày đặt: ");

        jLabel4.setText("Ngày trả: ");

        cbMaNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn nhân viên--" }));

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("ĐẶT PHÒNG");

        cbTenPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn Phòng--" }));

        jLabel2.setText("Tên phòng :");

        jLabel6.setText("Mã nhân viên: ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn dịch vụ"));

        ckcSuoiNong.setText("Suối nước nóng");

        ckcGiatLa.setText("Giặt là");

        ckcMassage.setText("Massage");

        ckcNhaHang.setText("Nhà hàng");

        ckcTennis.setText("Sân Golf/Tennis");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(ckcSuoiNong)
                .addGap(18, 18, 18)
                .addComponent(ckcGiatLa)
                .addGap(18, 18, 18)
                .addComponent(ckcMassage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ckcTennis)
                .addGap(18, 18, 18)
                .addComponent(ckcNhaHang))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckcSuoiNong)
                    .addComponent(ckcGiatLa)
                    .addComponent(ckcMassage)
                    .addComponent(ckcTennis)
                    .addComponent(ckcNhaHang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách khách hàng"));

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên KH", "CMND", "Quốc tịch", "Giới tính", "Tuổi", "SĐT"
            }
        ));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblKhachHangMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);

        btnThemKhachHang.setText("Thêm khách hàng");
        btnThemKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKhachHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThemKhachHang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jdateNgaydat, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jdateNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbMaNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbTenPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jdateNgaydat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdateNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXacNhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHuy)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        mdiDatPhong.this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
         xDrag = evt.getX();
         yDrag = evt.getY();
        JFrame jFrame = (JFrame) evt.getSource();
        mdiDatPhong.this.setLocation(jFrame.getLocation().x+xDrag-xPress,jFrame.getLocation().y+yDrag-yPress);
    }//GEN-LAST:event_formMouseDragged

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        xPress = evt.getX();
        yPress = evt.getY();
    }//GEN-LAST:event_formMouseMoved

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        if(checkLoi()){
            dp.insert(new DatPhong(0, ngaydat, ngaytra, maphong, manv));
                int id = dp.getLast().getId();
            qp.updateTT(maphong);
            if(tblKhachHang.getRowCount()>0){
               for( int i = 0; i < tblKhachHang.getRowCount(); i++){
                    tenkh = (String) tblKhachHang.getValueAt(i,0);
                    cmnd = (String) tblKhachHang.getValueAt(i, 1);
                    quoctich = (String) tblKhachHang.getValueAt(i, 2);
                    gioitinh = (String) tblKhachHang.getValueAt(i, 3);
                    tuoi = (int) tblKhachHang.getValueAt(i,4);
                    sdt = (String) tblKhachHang.getValueAt(i, 5);
                    qk.insert(new QLKhachHang(tenkh, cmnd, quoctich, gioitinh, tuoi, sdt, id));
               }
            }
            if(ckcGiatLa.isSelected()){
                dv.insert(new QlDichVu(0, "Giặt là",id,100000));
            }
            if(ckcMassage.isSelected()){
                dv.insert(new QlDichVu(0, "Massage",id,200000));
            }
            if(ckcSuoiNong.isSelected()){
                dv.insert(new QlDichVu(0, "Suối nước nóng",id,50000));
            }
            if(ckcNhaHang.isSelected()){
                dv.insert(new QlDichVu(0,"Nhà hàng",id, 40000));
            }
            if(ckcTennis.isSelected()){
                dv.insert(new QlDichVu(0,"Dịch vụ Tennis/Golf",id, 80000));
            }
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công ", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
   
//    JOptionPane.showMessageDialog(rootPane,tenkh + " " + tuoi, "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnThemKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKhachHangActionPerformed
        frmThemKhachHang f = new frmThemKhachHang();
        f.setLocationRelativeTo(null);
        f.setVisible(true);
        f.pack();
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnThemKhachHangActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void tblKhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMousePressed
        String tenkh = "";
        String cmnd = "";
        String  quoctich = "";
        String gioitinh = "";
        int cbIndex = 0;
        int tuoi = 0;
        String sdt = "";
        tenkh = (String) model.getValueAt(tblKhachHang.getSelectedRow(), 0);
        cmnd = (String) model.getValueAt(tblKhachHang.getSelectedRow(), 1);
        quoctich = (String) model.getValueAt(tblKhachHang.getSelectedRow(), 2);
        gioitinh = (String) model.getValueAt(tblKhachHang.getSelectedRow(), 3);
        tuoi = (int)model.getValueAt(tblKhachHang.getSelectedRow(), 4);
        sdt = (String) model.getValueAt(tblKhachHang.getSelectedRow(), 5);
        cbIndex = indexOfComboCountry.get(tblKhachHang.getSelectedRow());
        //JOptionPane.showMessageDialog(rootPane, tenkh + tuoi, "Lỗi", JOptionPane.INFORMATION_MESSAGE);
        
        frmThemKhachHang f = new frmThemKhachHang(tenkh, cmnd, quoctich, gioitinh, sdt, tuoi,cbIndex);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
        f.pack();
        f.setFocusable(true);
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_tblKhachHangMousePressed

    public static void addRowToTblKhachHang(Object[] dataRow){
        model = (DefaultTableModel) tblKhachHang.getModel();
        model.addRow(dataRow);
    }
    
    public static void deleteRowTblKhachHang(){
        //model = (DefaultTableModel) tblKhachHang.getModel();
        indexOfComboCountry.remove(tblKhachHang.getSelectedRow());
        model.removeRow(tblKhachHang.getSelectedRow());
    }
    
    public static void updateRowToTblKhachHang(String tenkh,String cmnd,String quoctich,String gioitinh,String sdt,int tuoi,int indexCountry){
        if(tblKhachHang.getSelectedRowCount()==1){
            model.setValueAt(tenkh,tblKhachHang.getSelectedRow(),0);
            model.setValueAt(cmnd,tblKhachHang.getSelectedRow(),1);
            model.setValueAt(quoctich,tblKhachHang.getSelectedRow(),2);
            model.setValueAt(gioitinh,tblKhachHang.getSelectedRow(),3);
            model.setValueAt(tuoi,tblKhachHang.getSelectedRow(),4);
            model.setValueAt(sdt,tblKhachHang.getSelectedRow(),5);
            indexOfComboCountry.set(tblKhachHang.getSelectedRow(),indexCountry);
        }
    }
    
    private boolean checkLoi(){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        maphong = qp.getMaPhong(cbTenPhong.getSelectedIndex());
        manv = nv.getManv(cbMaNV.getSelectedIndex());
        try{
        ngaydat = sdf.format(jdateNgaydat.getDate());
        ngaytra = sdf.format(jdateNgayTra.getDate());  
        if(getKhoangCachNgay(ngaydat, ngaytra)<=0){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập đúng định dạng ngày", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        }catch(Exception e){
              JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập đúng định dạng ngày", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
              return false;
        }
        if(cbMaNV.getSelectedIndex()==0 || cbTenPhong.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn phòng hoặc nhân viên", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
      
        return true;
    }
    /**
     * @param args the command line arguments
     */
    private float getKhoangCachNgay(String dayfrom,String dayto){
        long diff = 0;
        try{
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date1 = sdf.parse(dayfrom);
        Date date2 = sdf.parse(dayto);
        diff = date2.getTime() - date1.getTime();
        }catch(Exception e){
            e.printStackTrace();
        }
            return diff / (1000 * 60 * 60* 24);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mdiDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mdiDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mdiDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdiDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdiDatPhong().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThemKhachHang;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> cbMaNV;
    private javax.swing.JComboBox<String> cbTenPhong;
    private javax.swing.JCheckBox ckcGiatLa;
    private javax.swing.JCheckBox ckcMassage;
    private javax.swing.JCheckBox ckcNhaHang;
    private javax.swing.JCheckBox ckcSuoiNong;
    private javax.swing.JCheckBox ckcTennis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdateNgayTra;
    private com.toedter.calendar.JDateChooser jdateNgaydat;
    private static javax.swing.JTable tblKhachHang;
    // End of variables declaration//GEN-END:variables

    
}
