/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class mdiTroGiupPhanMem extends javax.swing.JInternalFrame {

    public mdiTroGiupPhanMem() {
        initComponents();
        startFrom();
    }

    private void startFrom() {
        pnTextTaiLieu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbbcauhoi2 = new javax.swing.JLabel();
        lbbCauhoi2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbbCauhoi1 = new javax.swing.JLabel();
        lbicon2 = new javax.swing.JLabel();
        pnTextTaiLieu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txTimTaiLieu = new javax.swing.JTextArea();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Câu hỏi thường gặp");

        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("x");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 0, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbbcauhoi2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbbcauhoi2.setText(" Tìm tài liệu");
        lbbcauhoi2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbbcauhoi2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbbcauhoi2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbbcauhoi2MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbbcauhoi2MouseReleased(evt);
            }
        });
        jPanel5.add(lbbcauhoi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 370, 50));

        lbbCauhoi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search (1).png"))); // NOI18N
        lbbCauhoi2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbbCauhoi2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbbCauhoi2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbbCauhoi2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbbCauhoi2MousePressed(evt);
            }
        });
        lbbCauhoi2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbbCauhoi2KeyPressed(evt);
            }
        });
        jPanel5.add(lbbCauhoi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 50));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 400, 50));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbbCauhoi1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbbCauhoi1.setText(" Tính bảo mật dữ liệu?");
        lbbCauhoi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbbCauhoi1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbbCauhoi1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbbCauhoi1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbbCauhoi1MouseReleased(evt);
            }
        });
        jPanel9.add(lbbCauhoi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 370, 50));

        lbicon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/verified.png"))); // NOI18N
        lbicon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbicon2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbicon2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbicon2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbicon2MousePressed(evt);
            }
        });
        lbicon2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbicon2KeyPressed(evt);
            }
        });
        jPanel9.add(lbicon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 50));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 400, 50));

        txTimTaiLieu.setEditable(false);
        txTimTaiLieu.setColumns(20);
        txTimTaiLieu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txTimTaiLieu.setRows(5);
        txTimTaiLieu.setText("  Sau khi đăng nhập vào hệ thống, tài liệu sẽ\nđược lưu trữ trong danh mục quản lí, ở đây\nta có thể tìm dữ liệu từng hóa đơn, phòng,.. ");
        txTimTaiLieu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane1.setViewportView(txTimTaiLieu);

        javax.swing.GroupLayout pnTextTaiLieuLayout = new javax.swing.GroupLayout(pnTextTaiLieu);
        pnTextTaiLieu.setLayout(pnTextTaiLieuLayout);
        pnTextTaiLieuLayout.setHorizontalGroup(
            pnTextTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        pnTextTaiLieuLayout.setVerticalGroup(
            pnTextTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        jPanel1.add(pnTextTaiLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 360, 250));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int check = JOptionPane.showConfirmDialog(rootPane, "Xác nhận thoát?", "Cảnh báo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (check == 0) {
            dispose();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lbbcauhoi2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbcauhoi2MouseEntered
        jPanel5.setBackground(Color.pink);
    }//GEN-LAST:event_lbbcauhoi2MouseEntered

    private void lbbCauhoi2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbbCauhoi2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbbCauhoi2KeyPressed

    private void lbbCauhoi2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbCauhoi2MouseEntered
        jPanel5.setBackground(Color.pink);
    }//GEN-LAST:event_lbbCauhoi2MouseEntered

    private void lbbcauhoi2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbcauhoi2MouseReleased
        jPanel5.setBackground(Color.white);
    }//GEN-LAST:event_lbbcauhoi2MouseReleased

    private void lbbCauhoi2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbCauhoi2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbbCauhoi2MousePressed

    private void lbbCauhoi2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbCauhoi2MouseExited
        jPanel5.setBackground(Color.white);
        pnTextTaiLieu.setVisible(false);
    }//GEN-LAST:event_lbbCauhoi2MouseExited

    private void lbbcauhoi2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbcauhoi2MouseExited
        jPanel5.setBackground(Color.white);
        pnTextTaiLieu.setVisible(false);
    }//GEN-LAST:event_lbbcauhoi2MouseExited

    private void lbbcauhoi2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbcauhoi2MouseClicked
        txTimTaiLieu.setText("  Tài liệu sẽ được lưu trữ trong danh mục\n"
                + " quản lí, ở đây ta có thể tìm dữ liệu từng\n"
                + " hóa đơn, phòng,.. ");
        pnTextTaiLieu.setVisible(true);

    }//GEN-LAST:event_lbbcauhoi2MouseClicked

    private void lbbCauhoi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbCauhoi1MouseClicked
        txTimTaiLieu.setText("  Mọi dữ liệu thông tin quan trọng đã được\n"
                + " mã hóa 100% nên bạn hoàn toàn\n"
                + " có thể yên tâm");
        pnTextTaiLieu.setVisible(true);
    }//GEN-LAST:event_lbbCauhoi1MouseClicked

    private void lbbCauhoi1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbCauhoi1MouseEntered
        jPanel9.setBackground(Color.pink);
    }//GEN-LAST:event_lbbCauhoi1MouseEntered

    private void lbbCauhoi1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbCauhoi1MouseExited
        jPanel9.setBackground(Color.white);
        pnTextTaiLieu.setVisible(false);
    }//GEN-LAST:event_lbbCauhoi1MouseExited

    private void lbbCauhoi1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbCauhoi1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lbbCauhoi1MouseReleased

    private void lbicon2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbicon2MouseEntered
        jPanel9.setBackground(Color.pink);
    }//GEN-LAST:event_lbicon2MouseEntered

    private void lbicon2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbicon2MouseExited
        jPanel9.setBackground(Color.white);
        pnTextTaiLieu.setVisible(false);
    }//GEN-LAST:event_lbicon2MouseExited

    private void lbicon2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbicon2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbicon2MousePressed

    private void lbicon2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbicon2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbicon2KeyPressed

    private void lbicon2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbicon2MouseClicked
        txTimTaiLieu.setText("  Mọi dữ liệu thông tin quan trọng đã được\n"
                + " mã hóa 100% nên bạn hoàn toàn\n"
                + " có thể yên tâm");
        pnTextTaiLieu.setVisible(true);
    }//GEN-LAST:event_lbicon2MouseClicked

    private void lbbCauhoi2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbCauhoi2MouseClicked
        txTimTaiLieu.setText("  Tài liệu sẽ được lưu trữ trong danh mục\n"
                + " quản lí, ở đây ta có thể tìm dữ liệu từng\n"
                + " hóa đơn, phòng,.. ");
        pnTextTaiLieu.setVisible(true);
    }//GEN-LAST:event_lbbCauhoi2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbbCauhoi1;
    private javax.swing.JLabel lbbCauhoi2;
    private javax.swing.JLabel lbbcauhoi2;
    private javax.swing.JLabel lbicon2;
    private javax.swing.JPanel pnTextTaiLieu;
    private javax.swing.JTextArea txTimTaiLieu;
    // End of variables declaration//GEN-END:variables
}
